Lotto/urls.py
from django.contrib import admin
from django.urls import path, include
from recommend.views import index


urlpatterns = [
    path('', index),
    path('admin/', admin.site.urls),
    path('recommend/', include('recommend.urls')),
    path('detail/<int:num>', include('recommend.urls')),
]

recommend/urls.py
from django.urls import path
from . import views

app_name = 'recommend'

urlpatterns = [
    path('<int:page>/', views.index, name='index'),
    path('detail/<int:num>', views.detail, name='detail'),
    path('numbers/', views.numbers, name='numbers'),
]

recommend/models.py
from django.db import models

class Numbers(models.Model):
    totSellamnt = models.IntegerField()
    drwNoDate = models.CharField(max_length=10)
    firstWinamnt = models.IntegerField()
    drwNo = models.IntegerField()
    drwtNo1 = models.IntegerField()
    drwtNo2 = models.IntegerField()
    drwtNo3 = models.IntegerField()
    drwtNo4 = models.IntegerField()
    drwtNo5 = models.IntegerField()
    drwtNo6 = models.IntegerField()
    bnusNo = models.IntegerField()
    firstPrzwnerCo = models.IntegerField()
    returnValue = models.CharField(max_length=20)
    firstAccumamnt = models.IntegerField()

recommend/views.py
from django.shortcuts import redirect, render
from  datetime import datetime
from .models import Numbers
import requests
from django.db.models import Q
from random import sample


numCounts = {}
numDates = {}
def refresh():
    for i in range(1, 46):
        numCounts[i] = 0
        numDates[i] = 0
    # 회차 계산
    now  = datetime.now()
    date_to_compare = datetime.strptime("20021207", "%Y%m%d")
    date_diff = now - date_to_compare
    num = int(date_diff.days/7)+1
    
    # 데이터 계산
    number_set = Numbers.objects.all()
    cnt = number_set.count()
    while cnt < num:
        cnt += 1
        url = 'https://www.dhlottery.co.kr/common.do?method=getLottoNumber&drwNo='+ str(cnt)
        response = requests.get(url).json()
        # 회차 초과시 중단
        if response['returnValue'] == 'fail': break
        Numbers.objects.create(**response)
    
    allNumbers = Numbers.objects.all()
    for n in range(1, 46):
        filteredNum = allNumbers.filter(
            Q(drwtNo1=n) | Q(drwtNo2=n) | Q(drwtNo3=n) | Q(drwtNo4=n) | Q(drwtNo5=n) | Q(drwtNo6=n) | Q(bnusNo=n)
            )
        numCounts[n] += filteredNum.count()
        numDates[n] = filteredNum.order_by('-pk')[0].pk
    return cnt

def index(request, page=1):
    now = datetime.today()
    cnt = refresh()
    allThing = Numbers.objects.all()
    allNumbers = allThing.order_by('-pk')[(page-1)*5:page*5]
    numbers = [
        {'drwNo':allNumbers[n].drwNo,
        'drwNoDate':allNumbers[n].drwNoDate,
        'nums': [
            allNumbers[n].drwtNo1,
            allNumbers[n].drwtNo2,
            allNumbers[n].drwtNo3,
            allNumbers[n].drwtNo4,
            allNumbers[n].drwtNo5,
            allNumbers[n].drwtNo6,
            allNumbers[n].bnusNo
            ]
        }
    for n in range(5)
    ]
    pages = list(range(1, (allThing.count()+1)//5))
    
    sortedNumbers = tuple(map(lambda x: x[0],sorted(numCounts.items(), key= lambda item: item[1])))
    sortedNumDates = tuple(map(lambda x: (x[0], x[1], cnt-x[1]),sorted(numDates.items(), key= lambda item: item[1])))
    
    sortedByDates = tuple(map(lambda x: x[0], sortedNumDates))

    tmp = [0]*46
    recommendNums = []
    for n in range(45):
        tmp[sortedByDates[n]] += 1
        if tmp[sortedByDates[n]] == 2:
            recommendNums.append(sortedByDates[n])
        tmp[sortedNumbers[n]] += 1
        if tmp[sortedNumbers[n]] == 2:
            recommendNums.append(sortedNumbers[n])
        


    context= {
        'numbers':numbers,
        'pages': pages,
        'bestNumbers': reversed(sortedNumbers[-6:]),
        'worstNumbers': sortedNumbers[:6],
        'longNums': sortedNumDates[:5],
        'recommendNums' : recommendNums[:10],
        'cnt': cnt,
        'now': now,
    }
    return render(request, 'recommend/index.html', context)

def detail(request, num):
    cnt = refresh()
    numCount = numCounts[num]
    allNumbers = Numbers.objects.all()
    allCount = allNumbers.count()
    winRate = round(numCount / allCount * 100, 2)
    lastWin = numDates[num]
    winDis =  cnt-lastWin
    recentWin5 = allNumbers.order_by('-pk').filter(
            Q(drwNo__gte=cnt-5) & (
                Q(drwtNo1=num) | Q(drwtNo2=num) | Q(drwtNo3=num) | Q(drwtNo4=num) | Q(drwtNo5=num) | Q(drwtNo6=num) | Q(bnusNo=num)
                )
            )
    recentWin10 = allNumbers.order_by('-pk').filter(
            Q(drwNo__gte=cnt-10) & (
                Q(drwtNo1=num) | Q(drwtNo2=num) | Q(drwtNo3=num) | Q(drwtNo4=num) | Q(drwtNo5=num) | Q(drwtNo6=num) | Q(bnusNo=num)
                )
            )

    context = {
        'num':num,
        'numCount': numCount,
        'allCount': allCount,
        'winRate': winRate,
        'lastWin': lastWin,
        'winDis': winDis,
        'recentWin5': recentWin5,
        'recentWin10': recentWin10,
    }
    return render(request, 'recommend/detail.html', context)

def numbers(request):
    refresh()
    sortedNumbers = tuple(map(lambda x: x[0],sorted(numCounts.items(), key= lambda item: item[1])))
    sortedNumDates = tuple(map(lambda x: (x[0]),sorted(numDates.items(), key= lambda item: item[1])))
    tmp = [0]*46
    recommendNums = []

    x = 0
    for n in range(45):
        tmp[sortedNumDates[n]] += 1
        if tmp[sortedNumDates[n]] == 2:
            recommendNums.append(sortedNumDates[n])
            x += 1
        tmp[sortedNumbers[n]] += 1
        if tmp[sortedNumbers[n]] == 2:
            recommendNums.append(sortedNumbers[n])
            x += 1
    
    num10 = recommendNums[:10]
    num20 = recommendNums[:20]
    recommendNums = []
    x = 0
    while x < 5:
        tmp = sample(num10, 6)
        if not tmp in recommendNums:
            recommendNums.append(tmp)
            x += 1
    
    while x < 10:
        tmp = sample(num20, 6)
        if not tmp in recommendNums:
            recommendNums.append(tmp)
            x += 1

    randomNums = []
    y = 0
    while y < 10:
        tmp = sample(range(1, 46), 6)
        if not tmp in randomNums:
            randomNums.append(tmp)
            y += 1

    context = {
        'recommendNums': recommendNums,
        'randomNums':randomNums,
    }
    return render(request, 'recommend/numbers.html', context)

recommend/templates/recommend/detail.html
{% extends 'base.html' %}

{% block content %}
  <div class="container box d-flex justify-content-center mt-3">
    {% if  num < 10 %}
      <div class="ball ball0 m-2">{{num}}</div>
    {% elif num < 20%}
      <div class="ball ball1 m-2">{{num}}</div>
    {% elif num < 30%}
      <div class="ball ball2 m-2">{{num}}</div>
    {% elif num < 40%}
      <div class="ball ball3 m-2">{{num}}</div>
    {% else %}
      <div class="ball ball4 m-2">{{num}}</div>
    {% endif %}

    <div style="width: 300px; text-align:left;">
      <p>당첨된 전체 게임 수: {{numCount}}</p>
      <p>총 당첨 확률: {{winRate}} %</p>
      <p>최근 5회 이내 당첨 정보:<p>
      <p>
        {% if recentWin5 %}
        {% for recentWin in recentWin5 %}
          ▶{{recentWin.drwNo}}회
        {% endfor %}
        {% else %}
        없음
        {% endif %}
      </p>
      <p>최근 10회 이내 당첨 정보:</p>
      <p>
        {% if recentWin10 %}
        {% for recentWin in recentWin10 %}
          ▶{{recentWin.drwNo}}회
        {% endfor %}
        {% else %}
        없음
        {% endif %}
      </p>
      <p>마지막 당첨: {{lastWin}}회</p>
      {% if winDis == 0 %}
        <p>가장 최근 회차에 당첨된 번호입니다.</p>
      {% else %}
        <p>최근 당첨으로부터 {{winDis}}주째..</p>
      {% endif %}
    </div>

  </div>
  <div class="m-3">
    <a href="{% url 'recommend:index' 1 %}"><button class="btn btn-dark">Home</button></a>
    <button id="go-back" class="btn btn-secondary">Back</button>
  </div>

{% endblock content %}

recommend/templates/recommend/index.html
{% extends 'base.html' %}

{% block content %}
<!--시간 표시-->
<p>{{now}}</p>

<!--추천 번호-->
<div class="container box">
  <h1 class="rec" style="color:yellow; text-shadow: 3px 3px red;"> 추천 번호 </h1>
  {% for num in recommendNums %}
  {% if  num < 10 %}
    <a style="text-decoration: none" href="{% url 'recommend:detail' num %}" class="ball ball0">{{num}} </a>
  {% elif num < 20%}
    <a style="text-decoration: none" href="{% url 'recommend:detail' num %}" class="ball ball1">{{num}} </a>
  {% elif num < 30%}
    <a style="text-decoration: none" href="{% url 'recommend:detail' num %}" class="ball ball2">{{num}} </a>
  {% elif num < 40%}
    <a style="text-decoration: none" href="{% url 'recommend:detail' num %}" class="ball ball3">{{num}} </a>
  {% else %}
    <a style="text-decoration: none" href="{% url 'recommend:detail' num %}" class="ball ball4">{{num}} </a>
  {% endif %}
  {% endfor %}
  
  <div class="d-flex justify-content-center">
    <a href="{% url 'recommend:numbers' %}"><button class="btn btn-dark m-2">더 보기</button></a>
    <a href="https://dhlottery.co.kr/"><button class="btn btn-danger m-2">복권 사러 가기</button></a>
  </div>
</div>
<!-- 당첨 내역 -->
<div class="container mt-3 box">
    <div class="d-flex justify-content-between">
      <h2 class="rec">이전 당첨 내역</h2>
      <div class="btn-group">
        <button class="btn btn-secondary dropdown-toggle m-2" type="button" data-bs-toggle="dropdown" aria-expanded="false">
          Pages
        </button>
        <ul class="dropdown-menu" style="height:30vh; overflow-y:scroll;">
          {% for page in pages %}
            <a class="dropdown-item" href="{% url 'recommend:index' page %}">{{page}}</a>
          {% endfor %}
        </ul>
      </div>
    </div>
    <table class="table table-dark table-striped" style="border: solid 1px darkgrey;">
      <tr class="table-dark">
        <th scope="col">회차</th>
        <th scope="col">번호</th>
        <th scope="col">추첨일</th>
      </tr>
      <tbody>
        {% for number in numbers %}
          <tr>
            <th class="table-dark">{{number.drwNo}}</th>
            <td class="table-dark">
              {% for num in number.nums %}
              {% if  num < 10 %}
                <a style="text-decoration: none" href="{% url 'recommend:detail' num %}" class="ball ball0">{{num}} </a>
              {% elif num < 20%}
                <a style="text-decoration: none" href="{% url 'recommend:detail' num %}" class="ball ball1">{{num}} </a>
              {% elif num < 30%}
                <a style="text-decoration: none" href="{% url 'recommend:detail' num %}" class="ball ball2">{{num}} </a>
              {% elif num < 40%}
                <a style="text-decoration: none" href="{% url 'recommend:detail' num %}" class="ball ball3">{{num}} </a>
              {% else %}
                <a style="text-decoration: none" href="{% url 'recommend:detail' num %}" class="ball ball4">{{num}} </a>
              {% endif %}
              {% endfor %}
            </td>
            <td class="table-dark">
              {{number.drwNoDate}}
            </td>
          </tr>
        {% endfor %}
      </tbody>
    </table>
    
    <!---->
    <div class="box p-3 row">
      <div class="box col-sm-12 col-md-6 align-middle">
        <div class="p-2">
          <h4 class="rec">최다 등장 번호</h4>
          {% for number in bestNumbers %}
          {% if  number < 10 %}
            <a style="text-decoration: none" href="{% url 'recommend:detail' number %}" class="ball ball0">{{number}} </a>
          {% elif number < 20%}
            <a style="text-decoration: none" href="{% url 'recommend:detail' number %}" class="ball ball1">{{number}} </a>
          {% elif number < 30%}
            <a style="text-decoration: none" href="{% url 'recommend:detail' number %}" class="ball ball2">{{number}} </a>
          {% elif number < 40%}
            <a style="text-decoration: none" href="{% url 'recommend:detail' number %}" class="ball ball3">{{number}} </a>
          {% else %}
            <a style="text-decoration: none" href="{% url 'recommend:detail' number %}" class="ball ball4">{{number}} </a>
          {% endif %}
          {% endfor %}
        </div>
        <br>
        <div class="p-2">
          <h4 class="rec">최소 등장 번호</h4>
          {% for number in worstNumbers %}
          {% if  number < 10 %}
            <a style="text-decoration: none" href="{% url 'recommend:detail' number %}" class="ball ball0">{{number}} </a>
          {% elif number < 20%}
            <a style="text-decoration: none" href="{% url 'recommend:detail' number %}" class="ball ball1">{{number}} </a>
          {% elif number < 30%}
            <a style="text-decoration: none" href="{% url 'recommend:detail' number %}" class="ball ball2">{{number}} </a>
          {% elif number < 40%}
            <a style="text-decoration: none" href="{% url 'recommend:detail' number %}" class="ball ball3">{{number}} </a>
          {% else %}
            <a style="text-decoration: none" href="{% url 'recommend:detail' number %}" class="ball ball4">{{number}} </a>
          {% endif %}
          {% endfor %}
        </div>
      </div>
      <div class="box col-sm-12 col-md-6">
        <div class="p-2">
          <h4 class="rec">최장 미당첨 번호</h4>
          <table class="table table-dark table-striped" style="border: solid 1px darkgrey;">
            <tr class="table-dark">
              <th scope="col">번호</th>
              <th scope="col">당첨 회차</th>
              <th scope="col">미당첨 주차</th>
            </tr>
            <tbody>
              {% for number in longNums %}
                <tr>
                  <th>
                    {% if  number.0 < 10 %}
                      <a style="text-decoration: none" href="{% url 'recommend:detail' number.0 %}" class="ball ball0">{{number.0}} </a>
                    {% elif number.0 < 20%}
                      <a style="text-decoration: none" href="{% url 'recommend:detail' number.0 %}" class="ball ball1">{{number.0}} </a>
                    {% elif number.0 < 30%}
                      <a style="text-decoration: none" href="{% url 'recommend:detail' number.0 %}" class="ball ball2">{{number.0}} </a>
                    {% elif number.0 < 40%}
                      <a style="text-decoration: none" href="{% url 'recommend:detail' number.0 %}" class="ball ball3">{{number.0}} </a>
                    {% else %}
                      <a style="text-decoration: none" href="{% url 'recommend:detail' number.0 %}" class="ball ball4">{{number.0}} </a>
                    {% endif %}
                  </th>
                  <td>{{number.1}}회</td>
                  <td>{{number.2}}회</td>
                </tr>
              {% endfor %}
            </tbody>
          </table>
        </div>
      </div>
    </div>


  </div>
{% endblock content %}

recommend/templates/recommend/numbers.html
{% extends 'base.html' %}

{% block content %}
  <div class="container">
    <div class="box row p-2">
      <div class="box col-sm-12 col-md-6">
        <h1>고확률 추천 번호</h1>
        <p>고확률 20개 번호에서 추출된 번호입니다.</p>
        <div class="box m-1">
          {% for numbers in recommendNums %}
            <p>
              <span style="font-size: 28px;">{{forloop.counter}}.</span>
              {% for num in numbers %}
                {% if  num < 10 %}
                  <a style="text-decoration: none" href="{% url 'recommend:detail' num %}" class="ball ball0">{{num}} </a>
                {% elif num < 20%}
                  <a style="text-decoration: none" href="{% url 'recommend:detail' num %}" class="ball ball1">{{num}} </a>
                {% elif num < 30%}
                  <a style="text-decoration: none" href="{% url 'recommend:detail' num %}" class="ball ball2">{{num}} </a>
                {% elif num < 40%}
                  <a style="text-decoration: none" href="{% url 'recommend:detail' num %}" class="ball ball3">{{num}} </a>
                {% else %}
                  <a style="text-decoration: none" href="{% url 'recommend:detail' num %}" class="ball ball4">{{num}} </a>
                {% endif %}
              {% endfor %}
            </p>
          {% endfor %}
        </div>
      </div>
      <div class="container box col-sm-12 col-md-6">
        <h1>랜덤 추천</h1>
        <p>랜덤하게 추출한 번호입니다.</p>
        <div class="box m-1">
          {% for numbers in randomNums %}
            <p>
              <span style="font-size: 28px;">{{forloop.counter}}.</span>
              {% for num in numbers %}
                {% if  num < 10 %}
                  <a style="text-decoration: none" href="{% url 'recommend:detail' num %}" class="ball ball0">{{num}} </a>
                {% elif num < 20%}
                  <a style="text-decoration: none" href="{% url 'recommend:detail' num %}" class="ball ball1">{{num}} </a>
                {% elif num < 30%}
                  <a style="text-decoration: none" href="{% url 'recommend:detail' num %}" class="ball ball2">{{num}} </a>
                {% elif num < 40%}
                  <a style="text-decoration: none" href="{% url 'recommend:detail' num %}" class="ball ball3">{{num}} </a>
                {% else %}
                  <a style="text-decoration: none" href="{% url 'recommend:detail' num %}" class="ball ball4">{{num}} </a>
                {% endif %}
              {% endfor %}
            </p>
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
  <div class="m-3">
    <a href="{% url 'recommend:index' 1 %}"><button class="btn btn-dark">Home</button></a>
    <button id="go-back" class="btn btn-secondary">Back</button>
  </div>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>로또-베스트</title>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
  <link rel="shortcut icon" type="image/png" href="{% static 'favicon.ico' %}"/>
  <style>
    .ball {
      display: inline-block;
      border-radius: 100%;
      text-align: center;
      vertical-align: middle;
      color: #fff;
      font-weight: 500;
      text-shadow: 0px 0px 2px rgb(0 0 0);
      text-shadow: 0px 0px 3px rgb(64 0 0 / 80%);
      width: 60px;
      height: 60px;
      line-height: 56px;
      font-size: 28px;
      border: solid 1px black
    }

    .ball:hover{
      font-size: 36px;
    }


    .ball0 {
      background: #fbc400;
    }
    .ball1 {
      background: #69c8f2;
    }
    .ball2 {
      background: #ff7272;
    }
    .ball3 {
      background: #aaa;
    }
    .ball4 {
      background: #b0d840;
    }
    .rec {
      -webkit-animation:blink 1s ease-in-out infinite alternate;
      -moz-animation:blink 1s ease-in-out infinite alternate;
      animation:blink 1s ease-in-out infinite alternate;
    }
    @-webkit-keyframes blink{ 0% {opacity:0.5;} 100% {opacity:1;} }
    @-moz-keyframes blink{ 0% {opacity:0.5;} 100% {opacity:1;} }
    @keyframes blink{ 0% {opacity:0.5;} 100% {opacity:1;} }

    
    .box {
      border: solid 1px darkgrey;"
    }

  </style>
</head>
<body style="background-color: black; color: white; text-align: center; vertical-align: middle; font-size: 18px;">
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
    <div class="container-fluid">
      <a class="navbar-brand" href="{% url 'recommend:index' 1 %}">로또 통계 정보</a>
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarNav">
        <ul class="navbar-nav">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDarkDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            숫자 정보
          </a>
          <ul class="dropdown-menu dropdown-menu-dark" aria-labelledby="navbarDarkDropdownMenuLink" style="height: 30vh; overflow-y: scroll">
            {% with ''|center:45 as range %}
            {% for _ in range %}
            <li><a class="dropdown-item" href="{% url 'recommend:detail' forloop.counter %}">{{ forloop.counter }}</a></li>
            {% endfor %}
            {% endwith %}
          </ul>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'recommend:numbers' %}">추천번호</a>
          </li>
        </ul>
      </div>
    </div>
  </nav>
  <div style="margin-top:80px; margin-bottom:60px;">
    {% block content %}
    {% endblock content %}
  </div>
  <div class="fixed-bottom" style="background-color: black;">
    Created by LEE, contact: wow8113@gmail.com
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ka7Sk0Gln4gmtz2MlQnikT1wXgYsOg+OMhuP+IlRH9sENBO0LRn5q+8nbTov4+1p" crossorigin="anonymous"></script>
  <script>
    document.getElementById('go-back').addEventListener('click', () => {
      window.history.back();
    });
  </script>
</body>
</html>